### ISSUE TITLE
synergys hang in XWindowsScreen::handleSystemEvent

### ISSUE THREAD

**Issue by brianjmurrell** [symless/synergy#5528]
Similar in nature (at least symptomatically) to #5447, here is another hang that happens on Linux.  In particular mine is Fedora 24 but I imagine this is distro agnostic.

This is a build from fd3ce6c3f6acfad837d0dd290e3f2cf558d8efcb.

```
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff701a430 in _XReply (dpy=dpy@entry=0x6f5010, rep=rep@entry=0x7fffffffd3e0, 
    extra=extra@entry=0, discard=discard@entry=1) at xcb_io.c:624
#2  0x00007ffff7010351 in XQueryPointer (dpy=0x6f5010, w=246, root=0x7fffffffd4b8, 
    child=0x7fffffffd4c0, root_x=0x7fffffffd4d8, root_y=0x7fffffffd4dc, win_x=0x7fffffffd4d0, 
    win_y=0x7fffffffd4d4, mask=0x7fffffffd470) at QuPntr.c:48
#3  0x00000000004632f2 in XWindowsScreen::handleSystemEvent(Event const&, void*) ()
#4  0x000000000044a06a in EventQueue::dispatchEvent(Event const&) ()
#5  0x000000000044bf5c in EventQueue::loop() ()
#6  0x000000000045764a in ServerApp::mainLoop() ()
#7  0x00000000004551ca in ServerApp::runInner(int, char**, ILogOutputter*, int (*)(int, char**))
    ()
#8  0x000000000045c679 in App::run(int, char**) ()
#9  0x000000000044107f in main ()
```

Last messages at DEBUG2 were:
```
[2016-08-09T10:49:45] DEBUG2: onMouseMoveSecondary -27,+9
[2016-08-09T10:49:45] DEBUG2: find neighbor on left of "laptop.example.com"
[2016-08-09T10:49:45] DEBUG2: "pc.interlinx.bc.ca" is on left of "laptop.example.com" at 0.125463
[2016-08-09T10:49:45] DEBUG1: try to leave "laptop.example.com" on left
[2016-08-09T10:49:45] DEBUG2: mapping state: 16
[2016-08-09T10:49:45] DEBUG2: |= modifier: 4
[2016-08-09T10:49:45] INFO: switch from "laptop.example.com" to "pc.interlinx.bc.ca" at 2669,240
[2016-08-09T10:49:45] DEBUG1: send leave to "laptop.example.com"
[2016-08-09T10:49:45] DEBUG2: writef(COUT)
[2016-08-09T10:49:45] DEBUG2: wrote 4 bytes
[2016-08-09T10:49:45] DEBUG2: mapping state: 16
[2016-08-09T10:49:45] DEBUG2: |= modifier: 4
[2016-08-09T10:49:45] DEBUG2: warped to 2669,240
[2016-08-09T10:49:45] INFO: entering screen
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x010031b6
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01009a54
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01009ae8
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01009b16
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01009b4b
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01009b92
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01009b98
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01009b9a
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01009b9c
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01009b9e
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x010196c0
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01000029
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x00400001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x00a00001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x00a0000b
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x00a0000e
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x00e00001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01000001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x0100000b
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01400001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01600001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01600003
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01800001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01a00001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01c00001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x02000001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x02200001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01800008
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01c00003
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x02800001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x02a00001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x02c00001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x0220003b
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x02600001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x00a00010
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x0100000d
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01000011
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01000012
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01000013
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03200001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03000001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01000019
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03000003
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x0100001b
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x02e00001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x02800008
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x0280001f
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03400001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03400002
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01000024
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x0280002a
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x02800026
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x0100317a
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x010031b3
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x010031b0
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01003872
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01003147
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x0100311a
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01004d56
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x010031ad
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x0100390d
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01004031
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x010255d6
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01006057
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03200040
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x0100003d
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x02200020
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e00001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e00003
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e00007
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03600001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03600099
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03a00001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03a00003
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03a00006
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03a0000e
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e00c21
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e00ed4
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e00f11
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e00c28
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e00c1a
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e04015
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e03013
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e045f1
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e04760
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e048e5
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e049e4
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e04a39
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e051e6
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e01143
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03a1ac65
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03a1ae34
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03a1ae38
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x04000001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x04000003
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x04200001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x04600001
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x04400003
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03a269e4
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e04d4e
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e050f8
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x0420004f
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x04000028
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x04200053
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x0360434c
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x0360437a
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03c00002
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03c00004
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03c00186
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03c0018e
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03400007
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x02000008
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x0360a2cc
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03c00030
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03c002e2
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03adcdb6
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03addf11
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03b01d42
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x0364b17d
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03c002d6
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03c002ea
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03b22740
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x01e5e0ed
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x042000c2
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03800004
[New Thread 0x7fffd67ec700 (LWP 23527)]
[2016-08-09T10:49:45] DEBUG1: thread 0x00000022 entry
[2016-08-09T10:49:45] DEBUG2: event: MotionNotify 2644,249
[2016-08-09T10:49:45] DEBUG2: event: MotionNotify 2644,249
[2016-08-09T10:49:45] DEBUG2: can't read property 524 on window 0x03800004
[2016-08-09T10:49:45] DEBUG2: event: MotionNotify 2620,259
[2016-08-09T10:49:45] DEBUG2: event: MotionNotify 2620,259
[2016-08-09T10:49:45] DEBUG2: event: MotionNotify 2597,270
[2016-08-09T10:49:45] DEBUG2: event: MotionNotify 2597,270

```

**Comment by brianjmurrell** [comment]
Just got this again:

```
[2016-08-10T09:27:07] DEBUG2: can't read property 524 on window 0x01f025e3
[2016-08-10T09:27:07] DEBUG2: can't read property 524 on window 0x01e5e0ed
[2016-08-10T09:27:07] DEBUG2: can't read property 524 on window 0x042000e3
[2016-08-10T09:27:07] DEBUG2: can't read property 524 on window 0x03800004
[New Thread 0x7fff48ed1700 (LWP 10675)]
[2016-08-10T09:27:07] DEBUG1: thread 0x00000140 entry
[2016-08-10T09:27:07] DEBUG2: msg from "laptop.example.com": CNOP
[2016-08-10T09:27:07] DEBUG2: no-op from
[2016-08-10T09:27:07] DEBUG2: msg from "laptop.example.com": DCLP
[2016-08-10T09:27:07] DEBUG2: readf(%1i%4i%1i%s)
[2016-08-10T09:27:07] DEBUG2: readf: read 1 byte integer: 0 (0x0)
[2016-08-10T09:27:07] DEBUG2: readf: read 4 byte integer: 317 (0x13d)
[2016-08-10T09:27:07] DEBUG2: readf: read 1 byte integer: 1 (0x1)
[2016-08-10T09:27:07] DEBUG2: readf: read 1 byte string: 4
[2016-08-10T09:27:07] DEBUG: start receiving clipboard data
[2016-08-10T09:27:07] DEBUG: receiving clipboard 0 size=4
[2016-08-10T09:27:07] DEBUG2: msg from "laptop.example.com": DCLP
[2016-08-10T09:27:07] DEBUG2: readf(%1i%4i%1i%s)
[2016-08-10T09:27:07] DEBUG2: readf: read 1 byte integer: 0 (0x0)
[2016-08-10T09:27:07] DEBUG2: readf: read 4 byte integer: 317 (0x13d)
[2016-08-10T09:27:07] DEBUG2: readf: read 1 byte integer: 2 (0x2)
[2016-08-10T09:27:07] DEBUG2: readf: read 4 byte string: 
[2016-08-10T09:27:07] DEBUG2: msg from "laptop.example.com": DCLP
[2016-08-10T09:27:07] DEBUG2: readf(%1i%4i%1i%s)
[2016-08-10T09:27:07] DEBUG2: readf: read 1 byte integer: 0 (0x0)
[2016-08-10T09:27:07] DEBUG2: readf: read 4 byte integer: 317 (0x13d)
[2016-08-10T09:27:07] DEBUG2: readf: read 1 byte integer: 3 (0x3)
[2016-08-10T09:27:07] DEBUG2: readf: read 0 byte string: 
[2016-08-10T09:27:07] DEBUG: received client "laptop.example.com" clipboard 0 seqnum=317, size=4
[2016-08-10T09:27:07] DEBUG2: msg from "laptop.example.com": DCLP
[2016-08-10T09:27:07] DEBUG2: readf(%1i%4i%1i%s)
[2016-08-10T09:27:07] DEBUG2: readf: read 1 byte integer: 1 (0x1)
[2016-08-10T09:27:07] DEBUG2: readf: read 4 byte integer: 317 (0x13d)
[2016-08-10T09:27:07] DEBUG2: readf: read 1 byte integer: 1 (0x1)
[2016-08-10T09:27:07] DEBUG2: readf: read 1 byte string: 4
[2016-08-10T09:27:07] DEBUG: start receiving clipboard data
[2016-08-10T09:27:07] DEBUG: receiving clipboard 1 size=4
[2016-08-10T09:27:07] DEBUG2: event: MotionNotify 2571,473
[2016-08-10T09:27:07] DEBUG2: event: MotionNotify 2571,473
[2016-08-10T09:27:07] DEBUG2: can't read property 524 on window 0x03800004
[2016-08-10T09:27:07] DEBUG: ignored screen "laptop.example.com" update of clipboard 0 (unchanged)
[2016-08-10T09:27:07] DEBUG2: event: MotionNotify 2487,462
[2016-08-10T09:27:07] DEBUG2: event: MotionNotify 2487,462
[2016-08-10T09:27:07] DEBUG2: msg from "laptop.example.com": DCLP
[2016-08-10T09:27:07] DEBUG2: readf(%1i%4i%1i%s)
[2016-08-10T09:27:07] DEBUG2: readf: read 1 byte integer: 1 (0x1)
[2016-08-10T09:27:07] DEBUG2: readf: read 4 byte integer: 317 (0x13d)
[2016-08-10T09:27:07] DEBUG2: readf: read 1 byte integer: 2 (0x2)
[2016-08-10T09:27:07] DEBUG2: readf: read 4 byte string: 
[2016-08-10T09:27:07] DEBUG2: msg from "laptop.example.com": DCLP
[2016-08-10T09:27:07] DEBUG2: readf(%1i%4i%1i%s)
[2016-08-10T09:27:07] DEBUG2: readf: read 1 byte integer: 1 (0x1)
[2016-08-10T09:27:07] DEBUG2: readf: read 4 byte integer: 317 (0x13d)
[2016-08-10T09:27:07] DEBUG2: readf: read 1 byte integer: 3 (0x3)
[2016-08-10T09:27:07] DEBUG2: readf: read 0 byte string: 
[2016-08-10T09:27:07] DEBUG: received client "laptop.example.com" clipboard 1 seqnum=317, size=4
[2016-08-10T09:27:07] DEBUG: ignored screen "laptop.example.com" update of clipboard 1 (unchanged)
^C
Thread 1 "synergys" received signal SIGUSR1, User defined signal 1.
pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185	62:	movl	(%rsp), %edi
(gdb) where
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff701a430 in _XReply (dpy=dpy@entry=0x6f5010, rep=rep@entry=0x7fffffffd3e0, 
    extra=extra@entry=0, discard=discard@entry=1) at xcb_io.c:624
#2  0x00007ffff7010351 in XQueryPointer (dpy=0x6f5010, w=246, root=0x7fffffffd4b8, 
    child=0x7fffffffd4c0, root_x=0x7fffffffd4d8, root_y=0x7fffffffd4dc, win_x=0x7fffffffd4d0, 
    win_y=0x7fffffffd4d4, mask=0x7fffffffd470) at QuPntr.c:48
#3  0x00000000004632f2 in XWindowsScreen::handleSystemEvent(Event const&, void*) ()
#4  0x000000000044a06a in EventQueue::dispatchEvent(Event const&) ()
#5  0x000000000044bf5c in EventQueue::loop() ()
#6  0x000000000045764a in ServerApp::mainLoop() ()
#7  0x00000000004551ca in ServerApp::runInner(int, char**, ILogOutputter*, int (*)(int, char**))
    ()
#8  0x000000000045c679 in App::run(int, char**) ()
#9  0x000000000044107f in main ()
(gdb) 

```

**Comment by XinyuHou** [comment]
@brianjmurrell 
Could you try out our latest release which is 1.8.2?
https://github.com/symless/synergy/releases/tag/v1.8.2-stable
