### ISSUE TITLE
synergys doesn't connect and gets SIGABRT when running as systemd user service

### ISSUE THREAD

**Issue by sassmann** [symless/synergy#6088]
### Operating Systems ###

Server: Fedora 25
Client: Fedora 25

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

Running a systemd user service with "systemctl --user enable synergys"
```
sassmann@w541:~ > cat /usr/lib/systemd/user/synergys.service
[Unit]
Description=Synergy Server Daemon
[Service]
Type=idle
ExecStart=/usr/bin/synergys --no-daemon --enable-crypto
Restart=on-failure
[Install]
WantedBy=default.target

```
Now on login synergys is started automatically. However although a client is running on another system they cannot connect. Running the client in foreground shows that it doesn't receive any messages from the server. Here's where the interesting part start. If attaching to synergys with gdb right after session login, after about 30 seconds synergys receives a SIGABRT.
```
sassmann@w541:~ > gdb -p 2104
[...]
Attaching to process 2104
[New LWP 2112]
[New LWP 2113]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
225     62:     movq    %rax, %r14
(gdb) c
Continuing.

Thread 1 "synergys" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      }
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fcf621ce4da in __GI_abort () at abort.c:89
#2  0x00007fcf621c4d67 in __assert_fail_base (fmt=<optimized out>,
    assertion=assertion@entry=0x560893116fef "s_screen == NULL",
    file=file@entry=0x560893117090 "/home/abuild/rpmbuild/BUILD/synergy-1.8."..., line=line@entry=127,
    function=function@entry=0x5608931176e0 <XWindowsScreen::XWindowsScreen(char const*, bool, bool, int, IEventQueue*__PRETTY_FUNCTION__> "XWindowsScreen::XWindowsScreen(const cha"...) at assert.c:92
#3  0x00007fcf621c4e12 in __GI___assert_fail (assertion=assertion@entry=0x560893116fef "s_screen == NULL",
    file=file@entry=0x560893117090 "/home/abuild/rpmbuild/BUILD/synergy-1.8."..., line=line@entry=127,
    function=function@entry=0x5608931176e0 <XWindowsScreen::XWindowsScreen(char const*, bool, bool, int, IEventQueue*__PRETTY_FUNCTION__> "XWindowsScreen::XWindowsScreen(const cha"...) at assert.c:101
#4  0x00005608930c6f8e in XWindowsScreen::XWindowsScreen (this=0x56089504fff0, displayName=0x0,
    isPrimary=<optimized out>, disableXInitThreads=<optimized out>, mouseScrollDelta=0, events=0x7fff88941290)
    at /usr/src/debug/synergy-1.8.8-stable/src/lib/platform/XWindowsScreen.cpp:127
#5  0x00005608930baffb in ServerApp::createScreen (this=0x7fff889411f0)
    at /usr/src/debug/synergy-1.8.8-stable/src/lib/synergy/ServerApp.cpp:589
#6  0x00005608930bc5b7 in ServerApp::openServerScreen (this=this@entry=0x7fff889411f0)
    at /usr/src/debug/synergy-1.8.8-stable/src/lib/synergy/ServerApp.cpp:501
#7  0x00005608930bcb36 in ServerApp::initServer (this=this@entry=0x7fff889411f0)
    at /usr/src/debug/synergy-1.8.8-stable/src/lib/synergy/ServerApp.cpp:454
#8  0x00005608930bd3b1 in ServerApp::retryHandler (this=0x7fff889411f0)
    at /usr/src/debug/synergy-1.8.8-stable/src/lib/synergy/ServerApp.cpp:421
#9  0x00005608930afb0a in EventQueue::dispatchEvent (this=0x7fff88941290, event=...)
    at /usr/src/debug/synergy-1.8.8-stable/src/lib/base/EventQueue.cpp:271
#10 0x00005608930b21cc in EventQueue::loop (this=0x7fff88941290)
    at /usr/src/debug/synergy-1.8.8-stable/src/lib/base/EventQueue.cpp:129
#11 0x00005608930bd92d in ServerApp::mainLoop (this=0x7fff889411f0)
    at /usr/src/debug/synergy-1.8.8-stable/src/lib/synergy/ServerApp.cpp:756
#12 0x00005608930bb13a in ServerApp::runInner (this=0x7fff889411f0, argc=3, argv=0x7fff88941788, outputter=0x0,
    startup=0x5608930bebf0 <standardStartupStatic(int, char**)>)
    at /usr/src/debug/synergy-1.8.8-stable/src/lib/synergy/ServerApp.cpp:800
#13 0x00005608930ba3d9 in App::run (this=0x7fff889411f0, argc=3, argv=0x7fff88941788)
    at /usr/src/debug/synergy-1.8.8-stable/src/lib/synergy/App.cpp:118
#14 0x00005608930a8a75 in main (argc=3, argv=0x7fff88941788)
    at /usr/src/debug/synergy-1.8.8-stable/src/cmd/synergys/synergys.cpp:49
```

After that synergys is restarted, per the systemd service file and now everything magically works. Client receives messages from server, everything ok. This is reproducible every single time.

**Comment by nlyan** [comment]
Running synergys frrom a systemd service file with no intermediate service program is not currently a supported scenario. 

v2.0 is introducing full service support on Linux.
